name: Test Obtener Secret

on:
  workflow_dispatch:

jobs:
  test-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar mensaje
        run: echo "Iniciando prueba de acceso a secretos"

      - name: Obtener y mostrar secreto
        run: |
          echo "El valor del secreto es: ${{ secrets.MI_SECRETO }}"
