name: Test Obtener Secret

on:
  push: 
    branches: 
      - ga-1
  workflow_dispatch:

jobs:
  test-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar mensaje
        run: echo "Iniciando prueba de acceso a secretos"

      - name: Verificar longitud del secreto
        run: |
          echo "Longitud del secreto: ${#TOKEN}"
          if [ -z "$TOKEN" ]; then
            echo "❌ El secreto está vacío o no está definido."
            exit 1
          else
            echo "✅ El secreto está definido correctamente."
          fi
        env:
          TOKEN: ${{ secrets.MI_SECRETO  }}
